### ISSUE TITLE
Mail subject is placed as malfunction link

### ISSUE THREAD

**Issue by r4dh4l** [leafac/www.kill-the-newsletter.com#11]
Hi,

I use https://www.kill-the-newsletter.com/ to send a newsletter to a [matrix](https://matrix.org/) room via [matrix RSS Bot](https://code.rix.si/rrix/matrix-feedbot). Everytime a newsletter arrives there is a link in the matrix room but it links to https://riot.im/app/. Any idea why this is the case?

However: It would be much better if there is just the mail subject as _plaintext_ posted.

**Comment by leafac** [comment]
> I use https://www.kill-the-newsletter.com/ to send a newsletter to a [matrix](https://matrix.org/) room via [matrix RSS Bot](https://code.rix.si/rrix/matrix-feedbot). Everytime a newsletter arrives there is a link in the matrix room but it links to https://riot.im/app/. Any idea why this is the case?

Sorry, but not really. The only thing I can be sure is that it has nothing to do with **Kill the Newsletter!**, because we don’t edit the content of the incoming emails in any way—we just add it as an entry in the feed.

> However: It would be much better if there is just the mail subject as _plaintext_ posted.

I’m not sure I understand what you mean. The subject of the incoming email should become the title of the entry in the feed. Do you see some other behavior?

Remember that you can test and find issues in your workflow by sending regular emails to your **Kill the Newsletter!** inbox.

**Comment by r4dh4l** [comment]
> I’m not sure I understand what you mean. The subject of the incoming email should become the title of the entry in the feed. Isn’t this what’s happening to you?

It is, but as a link to https://riot.im/app/ not to https://www.kill-the-newsletter.com/feeds/example.xml (this is what I would expect).

**Comment by leafac** [comment]
Entries in the feed created by **Kill the Newsletter!** don’t link anywhere ([note that there is no `<link>` tag here](https://github.com/leafac/www.kill-the-newsletter.com/blob/236302d5557f2b53bf0a7db61f7d91dbb624a72c/views/entry.erb)). So the link you’re seeing must have been added by the newsletter author or by the tools you’re using to consume the feed (for example, your feed reader or Matrix).
