### ISSUE TITLE
Discontinued?

### ISSUE THREAD

**Issue by kzssc** [leafac/www.kill-the-newsletter.com#49]
Hi there - thanks for the great app. Sad that I only manage to discover it yesterday. 

Has this project been discontinued? In disbelief, I tried out four newly created inboxes but none of them works. RSS reader can fetch the first entry (the welcome one w/ address + rss feed url) but nothing after that. Or is there some sort of trigger?

Thanks!

**Comment by leafac** [comment]
@kzssc: Thanks for reaching out.

This project is alive and well 🙌

It’s mostly feature-complete and more in maintenance mode.

I tested and everything seems to be updating in seconds. I’m afraid that maybe the issue you’re facing is related to your feed reader. Specially because the same issue doesn’t seem to happen on other feed readers. Maybe their support will be able to help you out.

If there’s anything I can do on my side to help, please let me know!

Best.

**Comment by kzssc** [comment]
Dear sender, 

Subject: Change of Email Domain

Starting from Friday, 3 January 2020, my personal email domain will gradually move to czhang.uk (from vpchris.com). Please save my new email address (same ***@***.*** (e.g., ***@***.***), and remove the current one from your system to avoid future disappointment.   Nevertheless this email has been forwarded, rest assured that you do not need to resend your message.   

Gracias.
 C.
